import type { INodeProperties } from 'n8n-workflow';

export const inventoryStockOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['inventoryStock'] } },
		options: [
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many stock entries',
				description: 'Get a list of stock entries',
			},
			{
				name: 'Remove',
				value: 'remove',
				action: 'Remove stock',
				description: 'Remove a quantity from stock at a location',
			},
		],
		default: 'getAll',
	},
];

export const inventoryStockFields: INodeProperties[] = [
	// ── Get Many ──────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['inventoryStock'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		displayOptions: {
			show: { resource: ['inventoryStock'], operation: ['getAll'], returnAll: [false] },
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: { minValue: 0 },
		displayOptions: {
			show: { resource: ['inventoryStock'], operation: ['getAll'], returnAll: [false] },
		},
		default: 0,
		description: 'Number of results to skip',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['inventoryStock'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Batch ID',
				name: 'batch_id',
				type: 'number',
				default: 0,
				description: 'Filter by batch ID',
			},
			{
				displayName: 'Batch Number',
				name: 'batch_number',
				type: 'string',
				default: '',
				description: 'Filter by batch number',
			},
			{
				displayName: 'Exclude Packed Quantities',
				name: 'exclude_packed_quantities',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude packed quantities from results',
			},
			{
				displayName: 'Hallway',
				name: 'hallway',
				type: 'string',
				default: '',
				description: 'Filter by location hallway',
			},
			{
				displayName: 'Level',
				name: 'level',
				type: 'string',
				default: '',
				description: 'Filter by location level',
			},
			{
				displayName: 'Location Name or ID',
				name: 'location_id',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getLocations' },
				default: '',
				description: 'Filter by storage location. Choose from the list, or specify an ID using an expression. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Location Type ID',
				name: 'location_type_id',
				type: 'number',
				default: 0,
				description: 'Filter by location type ID',
			},
			{
				displayName: 'Module',
				name: 'module',
				type: 'string',
				default: '',
				description: 'Filter by location module',
			},
			{
				displayName: 'Position',
				name: 'position',
				type: 'string',
				default: '',
				description: 'Filter by location position',
			},
			{
				displayName: 'Product Barcode',
				name: 'product_barcode',
				type: 'string',
				default: '',
				description: 'Filter by product barcode',
			},
			{
				displayName: 'Product ID',
				name: 'product_id',
				type: 'number',
				default: 0,
				description: 'Filter by product ID',
			},
			{
				displayName: 'Rack ID',
				name: 'rack_id',
				type: 'number',
				default: 0,
				description: 'Filter by rack ID',
			},
			{
				displayName: 'Row',
				name: 'row',
				type: 'string',
				default: '',
				description: 'Filter by location row',
			},
			{
				displayName: 'Stock State ID',
				name: 'stock_state_id',
				type: 'number',
				default: 0,
				description: 'Filter by stock state ID',
			},
			{
				displayName: 'Zone ID',
				name: 'zone_id',
				type: 'number',
				default: 0,
				description: 'Filter by zone ID',
			},
		],
	},

	// ── Remove ────────────────────────────────────────────────────────────────
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['inventoryStock'], operation: ['remove'] } },
		default: 0,
		description: 'ID of the product to remove from stock',
	},
	{
		displayName: 'Location Name or ID',
		name: 'locationId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getLocations' },
		required: true,
		displayOptions: { show: { resource: ['inventoryStock'], operation: ['remove'] } },
		default: '',
		description: 'Storage location to remove stock from. Choose from the list, or specify an ID using an expression. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Quantity',
		name: 'quantity',
		type: 'number',
		required: true,
		typeOptions: { minValue: 1 },
		displayOptions: { show: { resource: ['inventoryStock'], operation: ['remove'] } },
		default: 1,
		description: 'Number of units to remove',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['inventoryStock'], operation: ['remove'] } },
		options: [
			{
				displayName: 'Batch ID',
				name: 'batch_id',
				type: 'number',
				default: 0,
				description: 'ID of the specific batch to remove from',
			},
		],
	},
];
