import type { INodeProperties } from 'n8n-workflow';

export const productOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['product'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a product',
				description: 'Create a new product',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a product',
				description: 'Get a product by ID',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many products',
				description: 'Get a list of products',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a product',
				description: 'Update a product by ID',
			},
		],
		default: 'getAll',
	},
];

export const productFields: INodeProperties[] = [
	// ── Get Many ──────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['product'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		displayOptions: {
			show: { resource: ['product'], operation: ['getAll'], returnAll: [false] },
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: { minValue: 0 },
		displayOptions: {
			show: { resource: ['product'], operation: ['getAll'], returnAll: [false] },
		},
		default: 0,
		description: 'Number of results to skip',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: true,
				description: 'Whether to filter by active status',
			},
			{
				displayName: 'Article Number',
				name: 'article_number',
				type: 'string',
				default: '',
				description: 'Filter by article number',
			},
			{
				displayName: 'Barcode',
				name: 'barcode',
				type: 'string',
				default: '',
				description: 'Filter by product barcode',
			},
			{
				displayName: 'Management Type',
				name: 'management_type',
				type: 'options',
				options: [
					{ name: 'Lot', value: 'lot' },
					{ name: 'None', value: 'none' },
					{ name: 'Serial', value: 'serial' },
				],
				default: 'none',
				description: 'Filter by inventory management type',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Filter by product name',
			},
			{
				displayName: 'SKU',
				name: 'sku',
				type: 'string',
				default: '',
				description: 'Filter by product SKU',
			},
			{
				displayName: 'Third Party ID',
				name: 'third_party_id',
				type: 'string',
				default: '',
				description: 'Filter by supplier/third party ID',
			},
		],
	},

	// ── Get ───────────────────────────────────────────────────────────────────
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['product'], operation: ['get', 'update'] } },
		default: 0,
		description: 'ID of the product',
	},

	// ── Create ────────────────────────────────────────────────────────────────
	{
		displayName: 'SKU',
		name: 'sku',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		default: '',
		description: 'Stock keeping unit — unique product identifier',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		default: '',
		description: 'Product name',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		options: [
			{
				displayName: 'Article Number',
				name: 'article_number',
				type: 'string',
				default: '',
				description: 'Internal article reference number',
			},
			{
				displayName: 'Attributes (JSON)',
				name: 'attributes',
				type: 'json',
				default: '{}',
				description: 'Custom product attributes as a JSON object. Declare custom attribute field names to make them mappable in downstream steps.',
			},
			{
				displayName: 'Barcodes',
				name: 'barcodes',
				type: 'string',
				default: '',
				description: 'Comma-separated list of product barcodes',
			},
			{
				displayName: 'Cost Price',
				name: 'cost_price',
				type: 'number',
				default: 0,
				description: 'Product cost price',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'Product description',
			},
			{
				displayName: 'Height (Cm)',
				name: 'height',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'HS Code',
				name: 'hs_code',
				type: 'string',
				default: '',
				description: 'Harmonized System customs tariff code',
			},
			{
				displayName: 'Length (Cm)',
				name: 'length',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Management Type',
				name: 'management_type',
				type: 'options',
				options: [
					{ name: 'Lot', value: 'lot' },
					{ name: 'None', value: 'none' },
					{ name: 'Serial', value: 'serial' },
				],
				default: 'none',
				description: 'Inventory management type',
			},
			{
				displayName: 'Origin Country',
				name: 'origin_country',
				type: 'string',
				default: '',
				description: 'ISO country code of product origin',
			},
			{
				displayName: 'Sales Measure Units',
				name: 'sales_measure_units',
				type: 'string',
				default: '',
				description: 'Unit of measure for sales (e.g. pcs, kg)',
			},
			{
				displayName: 'Units Per Pallet',
				name: 'units_per_pallet',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Units Per Purchase Package',
				name: 'units_per_purchase_package',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Units Per Sales Package',
				name: 'units_per_sales_package',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Volume (Cm³)',
				name: 'volume',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Weight (Kg)',
				name: 'weight',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Width (Cm)',
				name: 'width',
				type: 'number',
				default: 0,
			},
		],
	},

	// ── Update ────────────────────────────────────────────────────────────────
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['update'] } },
		options: [
			{
				displayName: 'Article Number',
				name: 'article_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Attributes (JSON)',
				name: 'attributes',
				type: 'json',
				default: '{}',
				description: 'Custom product attributes as a JSON object',
			},
			{
				displayName: 'Barcodes',
				name: 'barcodes',
				type: 'string',
				default: '',
				description: 'Comma-separated list of product barcodes',
			},
			{
				displayName: 'Cost Price',
				name: 'cost_price',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Height (Cm)',
				name: 'height',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'HS Code',
				name: 'hs_code',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Length (Cm)',
				name: 'length',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Management Type',
				name: 'management_type',
				type: 'options',
				options: [
					{ name: 'Lot', value: 'lot' },
					{ name: 'None', value: 'none' },
					{ name: 'Serial', value: 'serial' },
				],
				default: 'none',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Origin Country',
				name: 'origin_country',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Sales Measure Units',
				name: 'sales_measure_units',
				type: 'string',
				default: '',
			},
			{
				displayName: 'SKU',
				name: 'sku',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Units Per Pallet',
				name: 'units_per_pallet',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Units Per Purchase Package',
				name: 'units_per_purchase_package',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Units Per Sales Package',
				name: 'units_per_sales_package',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Volume (Cm³)',
				name: 'volume',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Weight (Kg)',
				name: 'weight',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Width (Cm)',
				name: 'width',
				type: 'number',
				default: 0,
			},
		],
	},
];
