import type { INodeProperties } from 'n8n-workflow';

export const salesOrderOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['salesOrder'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a sales order',
				description: 'Create a new sales order',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a sales order',
				description: 'Get a sales order by ID',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many sales orders',
				description: 'Get a list of sales orders',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a sales order',
				description: 'Update a sales order by ID',
			},
		],
		default: 'getAll',
	},
];

export const salesOrderFields: INodeProperties[] = [
	// ── Get Many ──────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['salesOrder'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		displayOptions: {
			show: { resource: ['salesOrder'], operation: ['getAll'], returnAll: [false] },
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: { minValue: 0 },
		displayOptions: {
			show: { resource: ['salesOrder'], operation: ['getAll'], returnAll: [false] },
		},
		default: 0,
		description: 'Number of results to skip',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['salesOrder'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Channel',
				name: 'channel',
				type: 'string',
				default: '',
				description: 'Filter by sales channel',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'string',
				default: '',
				description: 'Filter by customer ID',
			},
			{
				displayName: 'Criterium',
				name: 'criterium',
				type: 'string',
				default: '',
				description: 'Filter by order criterium',
			},
			{
				displayName: 'Delivery Date',
				name: 'delivery_date',
				type: 'string',
				default: '',
				description: 'Filter by delivery date (format: YYYY-MM-DD hh:mm:ss)',
			},
			{
				displayName: 'Inserted At',
				name: 'inserted_at',
				type: 'string',
				default: '',
				description: 'Filter by creation date (format: YYYY-MM-DD hh:mm:ss)',
			},
			{
				displayName: 'Order Number',
				name: 'order_num',
				type: 'string',
				default: '',
				description: 'Filter by order reference number',
			},
			{
				displayName: 'Product ID',
				name: 'product_id',
				type: 'number',
				default: 0,
				description: 'Filter orders containing this product ID',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'options',
				options: [
					{ name: 'Cancelled', value: 'cancelled' },
					{ name: 'Ended', value: 'ended' },
					{ name: 'Packing', value: 'packing' },
					{ name: 'Picking', value: 'picking' },
					{ name: 'Queue', value: 'queue' },
				],
				default: 'queue',
				description: 'Filter by order state',
			},
			{
				displayName: 'Third Party ID',
				name: 'third_party_id',
				type: 'number',
				default: 0,
				description: 'Filter by customer (third party) ID',
			},
			{
				displayName: 'Updated At',
				name: 'updated_at',
				type: 'string',
				default: '',
				description: 'Filter by last update date (format: YYYY-MM-DD hh:mm:ss)',
			},
			{
				displayName: 'Warehouse ID',
				name: 'warehouse_id',
				type: 'number',
				default: 0,
				description: 'Filter by warehouse ID',
			},
		],
	},

	// ── Get / Update ──────────────────────────────────────────────────────────
	{
		displayName: 'Sales Order ID',
		name: 'salesOrderId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['salesOrder'], operation: ['get', 'update'] } },
		default: 0,
		description: 'ID of the sales order',
	},

	// ── Create ────────────────────────────────────────────────────────────────
	{
		displayName: 'Order Number',
		name: 'orderNum',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['salesOrder'], operation: ['create'] } },
		default: '',
		description: 'Unique reference number for the sales order',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['salesOrder'], operation: ['create'] } },
		options: [
			{
				displayName: 'Attributes (JSON)',
				name: 'attributes',
				type: 'json',
				default: '{}',
				description: 'Custom sales order attributes as a JSON object',
			},
			{
				displayName: 'Channel',
				name: 'channel',
				type: 'string',
				default: '',
				description: 'Sales channel (e.g. web, marketplace)',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'string',
				default: '',
				description: 'Customer identifier',
			},
			{
				displayName: 'Client Name',
				name: 'client_name',
				type: 'string',
				default: '',
				description: 'Customer name',
			},
			{
				displayName: 'Criterium',
				name: 'criterium',
				type: 'string',
				default: '',
				description: 'Order criterium or grouping label',
			},
			{
				displayName: 'Delivery Date',
				name: 'delivery_date',
				type: 'string',
				default: '',
				description: 'Expected delivery date (format: YYYY-MM-DD hh:mm:ss)',
			},
			{
				displayName: 'Destination Warehouse ID',
				name: 'destination_warehouse_id',
				type: 'number',
				default: 0,
				description: 'ID of the destination warehouse for transfers',
			},
			{
				displayName: 'External Order Number',
				name: 'external_order_num',
				type: 'string',
				default: '',
				description: 'External system reference number',
			},
			{
				displayName: 'Items (JSON)',
				name: 'items',
				type: 'json',
				default: '[]',
				description: 'Array of sales order line items. Each item: { product_id, quantity, line_order_id?, notes? }.',
			},
			{
				displayName: 'Merchant Channel ID',
				name: 'merchant_channel_id',
				type: 'number',
				default: 0,
				description: 'Merchant channel ID to associate with',
			},
			{
				displayName: 'Merchant ID',
				name: 'merchant_id',
				type: 'number',
				default: 0,
				description: 'Merchant ID to associate with',
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				default: '',
				description: 'Additional notes for the sales order',
			},
			{
				displayName: 'Priority',
				name: 'priority',
				type: 'number',
				default: 0,
				description: 'Order priority (lower number = higher priority)',
			},
			{
				displayName: 'Ship To (JSON)',
				name: 'ship_to',
				type: 'json',
				default: '{}',
				description: 'Shipping address as a JSON object',
			},
			{
				displayName: 'Shipping Method ID',
				name: 'shipping_method_id',
				type: 'number',
				default: 0,
				description: 'ID of the shipping method to use',
			},
			{
				displayName: 'Third Party ID',
				name: 'third_party_id',
				type: 'number',
				default: 0,
				description: 'ID of the customer (third party)',
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'string',
				default: '',
				description: 'Type of sales order',
			},
			{
				displayName: 'Warehouse ID',
				name: 'warehouse_id',
				type: 'number',
				default: 0,
				description: 'ID of the source warehouse',
			},
		],
	},

	// ── Update ────────────────────────────────────────────────────────────────
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['salesOrder'], operation: ['update'] } },
		options: [
			{
				displayName: 'Attributes (JSON)',
				name: 'attributes',
				type: 'json',
				default: '{}',
			},
			{
				displayName: 'Channel',
				name: 'channel',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Client Name',
				name: 'client_name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Criterium',
				name: 'criterium',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Delivery Date',
				name: 'delivery_date',
				type: 'string',
				default: '',
				description: 'Expected delivery date (format: YYYY-MM-DD hh:mm:ss)',
			},
			{
				displayName: 'Destination Warehouse ID',
				name: 'destination_warehouse_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'External Order Number',
				name: 'external_order_num',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Items (JSON)',
				name: 'items',
				type: 'json',
				default: '[]',
				description: 'Array of sales order line items. Each item: { product_id, quantity, line_order_id?, notes? }.',
			},
			{
				displayName: 'Merchant Channel ID',
				name: 'merchant_channel_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Merchant ID',
				name: 'merchant_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Order Number',
				name: 'order_num',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Priority',
				name: 'priority',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Ship To (JSON)',
				name: 'ship_to',
				type: 'json',
				default: '{}',
			},
			{
				displayName: 'Shipping Method ID',
				name: 'shipping_method_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Third Party ID',
				name: 'third_party_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Warehouse ID',
				name: 'warehouse_id',
				type: 'number',
				default: 0,
			},
		],
	},
];
