import type { INodeProperties } from 'n8n-workflow';

export const thirdPartyOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['thirdParty'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a third party',
				description: 'Create a new third party',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a third party',
				description: 'Get a third party by ID',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many third parties',
				description: 'Get a list of third parties',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a third party',
				description: 'Update a third party by ID',
			},
		],
		default: 'getAll',
	},
];

export const thirdPartyFields: INodeProperties[] = [
	// ── Get Many ──────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['thirdParty'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		displayOptions: {
			show: { resource: ['thirdParty'], operation: ['getAll'], returnAll: [false] },
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: { minValue: 0 },
		displayOptions: {
			show: { resource: ['thirdParty'], operation: ['getAll'], returnAll: [false] },
		},
		default: 0,
		description: 'Number of results to skip',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['thirdParty'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: true,
				description: 'Whether to filter by active status',
			},
			{
				displayName: 'ERP Code',
				name: 'erp_code',
				type: 'string',
				default: '',
				description: 'Filter by ERP code',
			},
			{
				displayName: 'ERP ID',
				name: 'erp_id',
				type: 'string',
				default: '',
				description: 'Filter by ERP ID',
			},
			{
				displayName: 'Identifier Number',
				name: 'identifier_number',
				type: 'string',
				default: '',
				description: 'Filter by alphanumeric identifier number',
			},
			{
				displayName: 'Identifier Type',
				name: 'identifier_type',
				type: 'string',
				default: '',
				description: 'Filter by identifier type',
			},
			{
				displayName: 'Merchant ID',
				name: 'merchant_id',
				type: 'number',
				default: 0,
				description: 'Filter by merchant ID',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Filter by third party name',
			},
			{
				displayName: 'Third Type',
				name: 'third_type',
				type: 'options',
				options: [
					{ name: 'Customer', value: 'C' },
					{ name: 'Supplier', value: 'S' },
				],
				default: 'S',
				description: 'Filter by type: supplier (S) or customer (C)',
			},
		],
	},

	// ── Get / Update ──────────────────────────────────────────────────────────
	{
		displayName: 'Third Party ID',
		name: 'thirdPartyId',
		type: 'number',
		required: true,
		displayOptions: { show: { resource: ['thirdParty'], operation: ['get', 'update'] } },
		default: 0,
		description: 'ID of the third party',
	},

	// ── Create ────────────────────────────────────────────────────────────────
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['thirdParty'], operation: ['create'] } },
		default: '',
		description: 'Name of the third party',
	},
	{
		displayName: 'Identifier Type',
		name: 'identifierType',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['thirdParty'], operation: ['create'] } },
		default: '',
		description: 'Type of identifier (e.g. NIF, CIF, Passport, VAT)',
	},
	{
		displayName: 'Identifier Number',
		name: 'identifierNumber',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['thirdParty'], operation: ['create'] } },
		default: '',
		description: 'Alphanumeric identifier number',
	},
	{
		displayName: 'Third Type',
		name: 'thirdType',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['thirdParty'], operation: ['create'] } },
		options: [
			{ name: 'Customer', value: 'C' },
			{ name: 'Supplier', value: 'S' },
		],
		default: 'S',
		description: 'Whether this is a supplier or customer',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['thirdParty'], operation: ['create'] } },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: true,
				description: 'Whether the third party is active',
			},
			{
				displayName: 'Attributes (JSON)',
				name: 'attributes',
				type: 'json',
				default: '{}',
				description: 'Custom attributes as a JSON object',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Email address of the third party',
			},
			{
				displayName: 'ERP Code',
				name: 'erp_code',
				type: 'string',
				default: '',
				description: 'Code of the third party in the ERP system',
			},
			{
				displayName: 'ERP ID',
				name: 'erp_id',
				type: 'string',
				default: '',
				description: 'ID of the third party in the ERP system',
			},
			{
				displayName: 'Merchant ID',
				name: 'merchant_id',
				type: 'number',
				default: 0,
				description: 'Merchant ID to associate the third party with',
			},
		],
	},

	// ── Update ────────────────────────────────────────────────────────────────
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['thirdParty'], operation: ['update'] } },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: true,
			},
			{
				displayName: 'Attributes (JSON)',
				name: 'attributes',
				type: 'json',
				default: '{}',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
			},
			{
				displayName: 'ERP Code',
				name: 'erp_code',
				type: 'string',
				default: '',
			},
			{
				displayName: 'ERP ID',
				name: 'erp_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Identifier Number',
				name: 'identifier_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Identifier Type',
				name: 'identifier_type',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Merchant ID',
				name: 'merchant_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Third Type',
				name: 'third_type',
				type: 'options',
				options: [
					{ name: 'Customer', value: 'C' },
					{ name: 'Supplier', value: 'S' },
				],
				default: 'S',
			},
		],
	},
];
